### ISSUE TITLE
Use Operator Framework for Instascale controller

### ISSUE THREAD

**Issue by asm582** [project-codeflare/instascale#64] opened 2023-04-27 20:41 UTC
@KPostOffice  should we close this issue in a different repo: https://github.com/openshift/machine-api-operator/issues/1138

**Comment by KPostOffice** [comment] 2023-04-28 15:19
Ahh, yes. My bad

**Comment by anishasthana** [comment] 2023-05-10 15:38
Is this effectively a dupe of https://github.com/project-codeflare/instascale/issues/47 and https://github.com/project-codeflare/instascale/issues/48?

**Comment by anishasthana** [comment] 2023-08-14 15:23
This is a duplicate of #47 and #48

**Closed by anishasthana** 2023-08-14 15:23 UTC
